# Generated by Django 5.0.1 on 2024-06-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="products/"),
        ),
    ]
