# Generated by Django 5.0.1 on 2024-06-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
    ]
